//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_S_App.Base
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Zakazs = new HashSet<Zakaz>();
        }

        public string GetPhoto
        {
            get
            {
                if (T_Photo == null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\images\" + T_Photo.Trim();
            }
        }



        public string GetColor
        {
            get
            {
                if (T_Destv_Skidka < 15)
                    return " #7fff00";
                else
                    return "#fff";
            }
        }
        public double ProductPriceWithDiscount
        {
            get
            {
                double p = Convert.ToDouble(T_Stoimost);
                byte d = Convert.ToByte(T_Destv_Skidka);
                double s = p * (100 - d) / 100;
                return s;
            }
        }
        public string GetTextDecotation
        {
            get
            {
                if (T_Destv_Skidka > 0)
                    return "Strikethrough";
                return null;
            }
        }

        public string T_Artikyl_ID { get; set; }
        public string T_Spisok_ID { get; set; }
        public int T_Ed_Izm_ID { get; set; }
        public double T_Stoimost { get; set; }
        public double T_Razmer_Max_Skidki { get; set; }
        public int T_Proizvod_ID { get; set; }
        public int T_Postavshik_ID { get; set; }
        public int T_Type_Tovar_ID { get; set; }
        public Nullable<double> T_Destv_Skidka { get; set; }
        public int T_Kolich { get; set; }
        public string T_Opis { get; set; }
        public string T_Photo { get; set; }
    
        public virtual Ed_Izm Ed_Izm { get; set; }
        public virtual Postavchik Postavchik { get; set; }
        public virtual Proizvod Proizvod { get; set; }
        public virtual Type_Tovara Type_Tovara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakazs { get; set; }
    }
}
