//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_S_App.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string U_Familya { get; set; }
        public string U_Imya { get; set; }
        public string U_Otchestvo { get; set; }
        public string U_Login { get; set; }
        public string U_Pass { get; set; }
        public int U_Role_ID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
