//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_S_App.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Zakaz_ID { get; set; }
        public string Z_Sostav { get; set; }
        public int Z_Kolich { get; set; }
        public System.DateTime Z_Data_Zakaza { get; set; }
        public System.DateTime Z_Data_Dostav { get; set; }
        public int Z_Pynkt_vid_ID { get; set; }
        public string Z_Famil { get; set; }
        public string Z_Imya { get; set; }
        public string Z_Otchestvo { get; set; }
        public int Z_Kod_Polych { get; set; }
        public int Z_Status_ID { get; set; }
    
        public virtual Pynkt_vid Pynkt_vid { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
